# SPDX-FileCopyrightText: © 2025 Authors of the roar-net-api-py project <https://github.com/roar-net/roar-net-api-py/blob/main/AUTHORS>
#
# SPDX-License-Identifier: CC0-1.0

repos:
- repo: local
  hooks:
  - id: ruff-check
    name: ruff-check
    entry: uv run -- ruff check
    language: unsupported
    types_or: [python, pyi]
    require_serial: true
  - id: ruff-format
    name: ruff-format
    entry: uv run -- ruff format
    language: unsupported
    types_or: [python, pyi]
    require_serial: true
  - id: mypy
    name: mypy
    entry: uv run -- mypy
    language: unsupported
    types_or: [python, pyi]
    require_serial: true
  - id: pytest
    name: pytest
    entry: uv run -- pytest -n auto
    language: unsupported
    types_or: [python]
    require_serial: true
- repo: https://codeberg.org/fsfe/reuse-tool
  rev: 9fabf9eb815a57aac116b435e8346c200cdb8604  # frozen: v6.2.0
  hooks:
  - id: reuse
